### ISSUE TITLE
Compilation fails in Linux / anaconda

### ISSUE THREAD

**Issue by manolomartinez** [madvn/infotheory#2]
This is the STDERR from `pip install --upgrade infotheory`, in a conda 4.7.5 environment in an up to date archlinux. Let me know if you need any further info.

Thanks!
Manolo
[pip.log](https://github.com/madvn/infotheory/files/3388671/pip.log)

**Comment by madvn** [comment]
Thanks for reporting, @manolomartinez 
Looks like it might be an Archlinux issue. See this - 
https://bbs.archlinux.org/viewtopic.php?id=242682

Let me know if this doesn't help. I'll reopen the issue. Thanks.
