### ISSUE TITLE
Feature request: Conditional mutual information and transfer entropy

### ISSUE THREAD

**Issue by perevo** [madvn/infotheory#3]
Can this toolbox be used to calculate conditional mutual information and transfer entropy?

**Comment by madvn** [comment]
Hi! 

Sorry for the delay in getting back to you. As it stands, you can use this package to estimate transfer entropy as explained by this paper - [https://arxiv.org/pdf/1102.1507.pdf](https://arxiv.org/pdf/1102.1507.pdf).

If you make 3 variables from your data, X(t), Y(t-k) and X(t-k), i.e. each data point you add using `it.add_data_point(np.concatenate([x_t, y_t_k, x_t_k])`, then you can estimate transfer from Y to X as

te = Unique info from Y(t-k) about X(t) + Synergistic info from Y(t-k) and X(t-k) about X(t)

You can estimate unique and synergistic information as shown [here](http://mcandadai.com/infotheory/measures.html#pid_title).

I am not sure about conditional entropy. Will get back to you in a while. 

Thanks for your interest in the package. Do email me at madvncv[at]gmail.com if you have more questions.
